### ISSUE TITLE
Add Info for Metadata ISO 19115

### ISSUE THREAD

**Issue by antje-s** [wmo-im/wcmp#117]
Another improvement could be an information for metadata that have specified e.g. ISO 19115 as metadata standard and not WMCP.  

Example:
urn%3Ax-wmo%3Amd%3Aint.wmo.wis%3A%3ASTAC21ENBJ.xml
```
 <gmd:metadataStandardName>
    <gco:CharacterString>ISO 19115-2 Geographic information — Metadata — Part 2: Extensions for imagery and gridded data</gco:CharacterString>
  </gmd:metadataStandardName>
  <gmd:metadataStandardVersion>
    <gco:CharacterString>ISO 19115-2:2009-02-15</gco:CharacterString>
  </gmd:metadataStandardVersion>

```
kpi validate result:

> "kpi_001": {
>         "name": "KPI-1: WCMP 1.3, Part 2 Compliance",
>         "total": 13,
>         "score": 9,
>         "comments": [
>             "ASSERTION ERROR: Requirement 8.2.1: Each WIS Discovery Metadata record shall include at least one keyword from the WMO_CategoryCode code list.",
>             "ASSERTION ERROR: Requirement 8.2.2: Keywords from WMO_CategoryCode code list shall be defined as keyword type \"theme\".",
>             "ASSERTION ERROR: Requirement 8.2.3: All keywords sourced from a particular keyword thesaurus shall be grouped into a single instance of the MD_Keywords class.",
>             "ASSERTION ERROR: Requirement 9.3.2: A WIS Discovery Metadata record describing data for global exchange via the WIS shall indicate the GTS Priority as Legal Constraint (type: \"otherConstraints\") using one and only one term from the WMO_GTSProductCategoryCode code list. Please check contraints at lines [286, 289]."
>         ],
>         "percentage": 69.231
>     },
> ...
> "percentage": 55.882,
>         "identifier": [
>             "urn:x-wmo:md:int.wmo.wis::STAC21ENBJ"
>         ],
>         "grade": "U"
> ...

Here, a note would possibly be good that this metadata record is not based on WMCP as metadata standard and therefore no KPI check is executed. In addition an info could follow if the metadata record is valid according to e.g. ISO 19115.
Which ISO standards should be allowed/ checked alternatively?

**Comment by tomkralidis** [comment]
(FYI transfered issue from pywcmp)


@antje-s thanks for the feedback. Perhaps we could add a KPI for metadata standard identification (the value as put forth in WCMP Part 1, Section 7:

```
7. DECLARING COMPLIANCE WITH THE WMO CORE METADATA PROFILE

A WIS discovery metadata record may declare compliance with this version of the WMO Core Metadata Profile as follows:

- /gmd:MD_Metadata/gmd:metadataStandardName = “WMO Core Metadata Profile of ISO 19115 (WMO Core), 2003/Cor.1:2006 (ISO 19115), 2007 (ISO/TS 19139)”
- /gmd:MD_Metadata/gmd:metadataStandardversion = “1.3”
```

`WMO Core Metadata Profile of ISO 19115 (WMO Core), 2003/Cor.1:2006 (ISO 19115), 2007 (ISO/TS 19139)`

Given the above ("MAY") I think we should add a KPI proper.  In hindsight, this would have been a valuable assertion to have in the ATS of WCMP at the time.

**Comment by josusky** [comment]
Well, the **pywcmp** tool was designed with **WCMP** 1.3 in mind. We could add a detection of the standard and if it is not WCMP 1.3 then do one of the followings:
* Stop the validation and print some friendly apology.
* Do a validation against schema (XSD), if available and print results ... and a friendly apology that we cannot provide anything better (no KPI measurement) at the moment ;-)

Seriously, some of the KPIs, like the title or abstract checking are generic and could be used for other metadata formats (as long as we know how to can extract those attributes from the XML) but some others are very WCMP specific. Do you want me to suppress those WCMP specific checks for non-WCMP metadata and calculate KPI score for the rest?

**Comment by josusky** [comment]
If a metadata XML document is a superset of WCMP, i.e. it conforms to WCMP and to something else at the same time, than we do not need to change the pywcmp tool. It will do its job of validating WCMP KPIs. The extra elements needs to be checked by some other tool (or pywcmp can be embedded into some tool that does validation of this superset).
But if the metadata XML marked with some other metadataStandardName is not WCMP compliant then why should be pywcmp used on it?
BTW, the metadataStandardName is (usually?) stored as a character string and does not seem to be used consistently (here are 4 examples that a quick grep yielded):

```
<gco:CharacterString>WMO Core Metadata Profile of ISO 19115 (WMO Core), 2003/Cor.1:2006 (ISO 19115), 2007 (ISO/TS 19139)</gco:CharacterString>

<gco:CharacterString xmlns:gco="http://www.isotc211.org/2005/gco">WMO Core Metadata Profile of ISO 19115 (WMO Core), 2003/Cor.1:2006 (ISO 19115), 2007 (ISO/TS 19139)</gco:CharacterString>

<gco:CharacterString>WMO Core Profile of ISO 19115</gco:CharacterString>

<gco:CharacterString>ISO19115 / GAW-WDCA Profile</gco:CharacterString>
```

**Comment by tomkralidis** [comment]
Update TT-WISMD 2021-06-04: given providers may be publishing ISO metadata for multiple purposes (superset), as well as the the value of `gmd:metadataStandardName` being long and error prone, we decided to not add/implement this as a KPI.
