### ISSUE TITLE
Prepare KPIs for publication into WMO-No. 1061

### ISSUE THREAD

**Issue by amilan17** [wmo-im/wcmp#128]
The KPIs will get published to the Guide to WIS (WMO-No. 1061) in section 5.9 and it needs to be modified to fit with the "style" of the guide. The KPIs for WCMP 1.3 will be setting the stage for how we publish and implement KPIs in WIS2. 

These are some things that I feel need to change before publication.  

*    [x]  Don't refer to "this document"
*    [x]  re-organize the KPI layout (see revised template)
*    [x]  No fragmented sentences
*    [x]  Remove shall/should words from 'Measurement' description
*    [x]  Replace text copies of guidance (from the WIS guide) to references of the section in the guide.

**Comment by amilan17** [comment]
copy of doc with first review:
[wcmp-kpi-1.3-amReview.docx](https://github.com/wmo-im/wcmp/files/9020259/wcmp-kpi-1.3-amReview.docx)

**Comment by amilan17** [comment]
related issues: 

- [ ] #126 
- [ ] #125
- [ ] #105
- [ ]

**Comment by amilan17** [comment]
**KPI_002 Title**
Guidance to score is essentially a copy of 5.8.1.1 in the Guide to WIS. Given that these KPIs will go into section 5.9, I don't think we want to repeat content and we should just refer to existing guidance when it exists. HOWEVER, sometimes, there are conflicts between the the previous guidance and KPI guidance/rules. For example: 

`words in title are represented in "Title Case"`
versus the example title in the guidance: `SLSTR L1B radiances and brightness temperatures`

**Comment by josusky** [comment]
Hi @amilan17, I have checked more thoroughly the changes in KPI-9. You are completely right that it overlaps with the KPI-1 (ATS) but, there is a serious "but". It is not really a duplicate, it is a superset. The idea of the KPI-9 was to check the data license stuff and constraints **thoroughly** and @martaguti worked really hard on it. I remember that I got a serious headache when I was implementing it into `pywcmp`. Here is an example of legal constraints element that passes through KPI-1 (ATS) without issue, but does not pass through KPI-9 (please note that the first `gmd:MD_RestrictionCode` element with value `otherRestrictions` is commented-out, thus practically not existent):
```        <gmd:MD_LegalConstraints>
          <gmd:accessConstraints>
          <!--
            <gmd:MD_RestrictionCode codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/Codelist/gmxCodelists.xml#MD_RestrictionCode" codeListValue="otherRestrictions">otherRestrictions</gmd:MD_RestrictionCode>
          -->
          </gmd:accessConstraints>
          <gmd:useConstraints>
            <gmd:MD_RestrictionCode codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/Codelist/gmxCodelists.xml#MD_RestrictionCode" codeListValue="otherRestrictions">otherRestrictions</gmd:MD_RestrictionCode>
          </gmd:useConstraints>
          <gmd:otherConstraints>
            <gmx:Anchor xlink:href="http://wis.wmo.int/2012/codelists/WMOCodeLists.xml#WMO_DataLicenseCode">WMOOther</gmx:Anchor>
          </gmd:otherConstraints>
          <gmd:otherConstraints>
            <gmx:Anchor xlink:href="http://wis.wmo.int/2012/codelists/WMOCodeLists.xml#WMO_GTSProductCategoryCode">GTSPriority3</gmx:Anchor>
          </gmd:otherConstraints>
        </gmd:MD_LegalConstraints>```

I understand that it was written in a style that does not fit well into the Guide to WIS but your simplified version does not capture the original complexity. So we have two possible ways forward:

1. Restore the original @martaguti version with minimal editorial changes.
2. Simplify it even more and leave there only the "distribution links check" (9.1) - that was originally KPI-5.

**Comment by amilan17** [comment]
@josusky Had a deep dive into KPI-9 today and you are right -- these tests are now too simple and don't handle the complexity that we had before. I agree with you on restoring Marta's original version of tests with medium editorial updates (now to match the rest of the document) and the test for "WMOEssential". 

@tomkralidis ok?

**Comment by tomkralidis** [comment]
ok
