### ISSUE TITLE
Define the KPI A  WMO Core Profile and its mandatory elements

### ISSUE THREAD

**Issue by gaubert** [wmo-im/wcmp#16]

**Comment by efucile** [comment]
working on this branch https://github.com/wmo-im/wmcp/tree/KPI-A

**Comment by amilan17** [comment]
Schematron options: https://github.com/wmo-im/wmcp/tree/master/validationTestSuite

**Comment by efucile** [comment]
regarding the schemas in wis.wmo.int WMO publication 1060 says that:
"WMO hosts a copy of the ISO/TS 19139:2007 XML schemas at: 
http://wis.wmo.int/2011/schemata/iso19139_2007/
schema/. The directory structure in which the XML schemata are published 
mirrors that of the normative XML schema repository published by ISO at: 
http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/. 
For example, gmd.xsd can be found at 
http://wis.wmo.int/2011/schemata/iso19139_2007/schema/gmd/gmd.xsd."

**Comment by efucile** [comment]
Add more precision when defining “what is being measured” in https://github.com/wmo-im/wmcp/blob/master/KPI/A.adoc such that a developer can take the rules and implement it.

**Comment by gaubert** [comment]
@guillaudf is this KPI open for review. Could you please let us know ? Thanks.
