### ISSUE TITLE
Migrate the code list from wis.wmo.int to codes.wmo.int

### ISSUE THREAD

**Issue by gaubert** [wmo-im/wcmp#17]

**Comment by tomkralidis** [comment]
Questions/updates:
- should we continue to support the ISO codelist catalogue as well (guessing yes)?  If yes:
  - should this be published to http://wis.wmo.int/index.php?dir=/2013/codelists or https://schemas.wmo.int , or both?  I would suggest https://schemas.wmo.int moving forward, but I am unsure of what rules/policies/requirements exist around having to support http://wis.wmo.int
- I've put forth a PR in #57 to autogenerate the ISO codelist catalogue XML for review and comment
- what is the procedure and details on how to actually get this integrated into codes.wmo.int?

**Comment by amilan17** [comment]
I think we decided to NOT do this....

**Comment by amilan17** [comment]
related to #85

**Comment by tomkralidis** [comment]
Closing.  Note that we will provide this capability for WCMP2 codelists, at which point we can open another issue at that time.
