### ISSUE TITLE
Define the KPI B Good quality title

### ISSUE THREAD

**Issue by efucile** [wmo-im/wcmp#18]

**Comment by efucile** [comment]
working on this  branch https://github.com/wmo-im/wmcp/tree/KPI-B

**Comment by amilan17** [comment]
Don't need to verify that title exists, because it's already checked by schema validation.

**Comment by amilan17** [comment]
Programmatically evaluate that there too many acronyms in the title; too many is more than 3 acronyms and NOT only 1 acronym w/ no english words.

**Comment by amilan17** [comment]
title length should be at a minimum 3 words  and 150 characters

**Comment by amilan17** [comment]
Updated: https://github.com/wmo-im/wmcp/blob/KPI-B/KPI/B.adoc, but there are outstanding issues. 

1. How to programmatically recognize acronyms? 
2. Discuss the 'title case' recommendation. It differs from the WMCP guidance. 
3. The https://gisc.dwd.de/wisportal/# has many records with `[DRAFT]` in the title! Should we be testing for this? 
4. The 'printable characters' requirement needs more guidance... Do we mean ascii only?

**Comment by amilan17** [comment]
1. acronyms might be able, if you have a look up table and using the english dictionary. 
2. title case approved.
3. add a test for the word 'draft' in the title. 
4. In the conversation, trying to engineer a way to check against an english dictionary. Change to English words and letters. 
5. Do not include specific guidance for GTS Bulletins .... these are being removed. TTAAII CCC  requirements are being removed, but it will be difficult to change. 

@hermannasensio - provide an example of bulletins that don't have any information.

**Comment by hermannasensio** [comment]
there are a lot of automatic generated Bulletins, which only contain the TTAAII CCCC information, some are marked with [DRAFT] in the Title, some are not like 
https://gisc.dwd.de/wisportal/#SearchPlace:q?pid=urn:x-wmo:md:int.wmo.wis::IOSX05KWBC

**Comment by gaubert** [comment]
@hermannasensio Can we have an example of the STOPGAP records as well ?

We should detect automatically generated bulletin metadata and give a bad score. Apart from that this is open for review.

**Comment by josusky** [comment]
When it concerns acronyms, the examples actually contains acronyms too (e.g. "AMSR-2 Sea Surface Temperature"), thus I understand it so, that we are fine with one or two of them in the title but not three. Fair enough. It is also worth noting that certain acronyms are actually valid English words, such as "SWIM", thus I think that the only viable definition of the acronym, that can be checked in software, is: "a word that contains only uppercase letters and possibly some numbers", i.e. it could be checked with following regular  expression "[A-Z][A-Z0-9]+".

**Comment by josusky** [comment]
Hmm, I have checked a few more abbreviations, people are more inventive than it appears:
AoB
IPv6
X.400
3M
So probably a better definition is "a word that has uppercase letter somewhere in the middle". As we need to take into account also numbers (i.e. 12 is **not** an abbreviation), my new proposal is the following regex: "`([0-9]+[A-Z]+|[^0-9]+?[A-Z0-9]+).*`".

**Comment by tomkralidis** [comment]
Implemented in https://github.com/wmo-im/wcmp/pull/62
