### ISSUE TITLE
Define the KPI D Valid Station Identifier

### ISSUE THREAD

**Issue by efucile** [wmo-im/wcmp#20]

**Comment by efucile** [comment]
working on this branch https://github.com/wmo-im/wmcp/blob/KPI-D/KPI/D.adoc

**Comment by kateroberts** [comment]
To test for a station Id, might need to check for relevant thesaurus title variants? ['WMO codes', etc].

For the test for a station id:
Check that the Thesaurus element is used, and that the Thesaurus title matches XXX. 

ACTION: collect all the variants on thesaurus name, and identify the correct Thesaurus title wording, and related thesaurus content. 
ACTION: also update the Guidance doc, to reflect newer WIGOS Station ID format.

**Comment by tomkralidis** [comment]
cc @joergklausen 

I've updated the `KPI-D` [branch](https://github.com/wmo-im/wmcp/blob/KPI-D/KPI/D.adoc) accordingly.  Can anyone provide what the correct `gmd:thesaurusName` would be for WIGOS/OSCAR?  This would be the trigger to further execute this particular KPI.

**Comment by jsieland** [comment]
Comment from my GISC Offenbach colleagues:
- if place keyword is wigos-id (e.g. start with "0-20000-0-") request to oscar should return station details
- WIGOS-IDs of stations all included/mentioned in place keywords (separated for each ID one keyword section)

**Comment by joergklausen** [comment]
> 
> 
> cc @joergklausen
> 
> I've updated the `KPI-D` [branch](https://github.com/wmo-im/wmcp/blob/KPI-D/KPI/D.adoc) accordingly. Can anyone provide what the correct `gmd:thesaurusName` would be for WIGOS/OSCAR? This would be the trigger to further execute this particular KPI.

I could suggest the following:
`<gmd:thesaurusName>
<gmd:CI_Citation>
<gmd:title>
<gco:CharacterString>OSCAR/Surface</gco:CharacterString>
</gmd:title>
<gmd:alternateTitle>
<gco:CharacterString>WIGOS Station Identifier (WSI) therausus API https://oscar.wmo.int/surface/rest/api/search/wigos?WIGOSStationIdentifier=<a-b-c-d>)
</gco:CharacterString>
</gmd:alternateTitle>
<gmd:date/>
</gmd:CI_Citation>
</gmd:thesaurusName>`
I invite other folks' input, though.

**Comment by tomkralidis** [comment]
Thanks @joergklausen . What about the following:

```xml
<gmd:thesaurusName>
  <gmd:CI_Citation>
    <gmd:title>
      <gmx:Anchor xlink:title="OSCAR/Surface" xlink:href="https://oscar.wmo.int/surface/rest/api/stations/approvedStations/wigosIds">OSCAR/Surface</gmx:Anchor>
    </gmd:title>
    <gmd:date>
      <gmd:CI_Date>
        <gmd:date gco:nilReason="inapplicable"/>
        <gmd:dateType gco:nilReason="inapplicable"/>
      </gmd:CI_Date>
    </gmd:date>
  </gmd:CI_Citation>
</gmd:thesaurusName>
```

The idea here would be to use `gmx:Anchor` (as per other KPIs) to be able to articulate both a human readable title as well as a URL which can be de-referenced accordingly.  I am putting forth https://oscar.wmo.int/surface/rest/api/stations/approvedStations/wigosIds as the URL here with the idea that the given WSI is in this list.

**Comment by joergklausen** [comment]
@tomkralidis Thanks, works for me.

**Comment by tomkralidis** [comment]
Thanks @joergklausen .  I've opened a subsequent PR in #83 for review/comment.
