### ISSUE TITLE
Define KPI H Keywords

### ISSUE THREAD

**Issue by efucile** [wmo-im/wcmp#24]

**Comment by efucile** [comment]
working on this branch https://github.com/wmo-im/wmcp/blob/KPI-H/KPI/H.adoc

**Comment by efucile** [comment]
higher score if you have type and thesaurus when a dataParam is present. For @martaguti to express clearly this concept in the document.

**Comment by amilan17** [comment]
Change KPI for all relevant keywords. 

See Guidance in https://library.wmo.int/doc_num.php?explnum_id=4004
5.8.1.8 Descriptive keywords

**Comment by martaguti** [comment]
@wmo-im/tt-wismd 
KPI H Keywords committed at: 
https://github.com/wmo-im/wmcp/blob/KPI-H/KPI/H.adoc

For review.

**Comment by martaguti** [comment]
KPI H Keywords updated to include an example of a high scoring keyword implementation that covers conformance with 8.2.1 (as discussed in the last TelCo)
8.2.1 Each WIS discovery metadata record shall include at least one keyword from the 
WMO_CategoryCode code list

**Comment by tomkralidis** [comment]
Implemented in https://github.com/wmo-im/wcmp/pull/63
