### ISSUE TITLE
Define KPI I GraphicOverview for non bulletins metadata records

### ISSUE THREAD

**Issue by efucile** [wmo-im/wcmp#25]

**Comment by efucile** [comment]
working on this branch https://github.com/wmo-im/wmcp/blob/KPI-I/KPI/I.adoc

**Comment by gaubert** [comment]
Hi all,

Please find in that KPI the proposal for the new refined template. It is shorter and structured as follow: 
### 1. What is being measured and why should it be measured

This part describes the context and why it should be measured.

### 2. To which WMCP element(s) does it apply ?

Which elements are targeted in the WMCP.

### 3. KPI implementation rules

This part describes the pseudo code and technical details to implement that KPI

### 4. Score Values

Here is described how the score should be calculated for that KPI.

### 5. Guidance to score well on this KPI

Additional guidance to help the metadata creator implementing the KPI can be added here.

You can check the following branch https://github.com/wmo-im/wmcp/blob/KPI-I/KPI/I.adoc and post your comments here as needed.
If this is fine please copy it in your own branches.

Thanks,
Guillaume

**Comment by gaubert** [comment]
@tomkralidis your updates regarding the scoring is fine with me. I would consider then this one complete.
