### ISSUE TITLE
Define KPI J  Broken links

### ISSUE THREAD

**Issue by efucile** [wmo-im/wcmp#26]

**Comment by efucile** [comment]
working on this branch https://github.com/wmo-im/wmcp/blob/KPI-J/KPI/J.adoc

**Comment by jsieland** [comment]
Comment from my GISC Offenbach colleagues:
- url values are only allowed in  gmd:URL, gmx:Anchor/@xlink:href, and @codeList elements/attributes (no CharacterString).
- so you can search for those tags and checkURL via script

**Comment by amilan17** [comment]
There is one exception: the browseGraphic has a field with a characterString, where it is acceptable to include a URL to the thumbnail image.

**Comment by tomkralidis** [comment]
Implemented in https://github.com/wmo-im/wcmp/pull/64
