### ISSUE TITLE
Define KPI K Data Policy Possible combination

### ISSUE THREAD

**Issue by efucile** [wmo-im/wcmp#27]

**Comment by efucile** [comment]
working on this branch https://github.com/wmo-im/wmcp/blob/KPI-K/KPI/K.adoc

**Comment by efucile** [comment]
@amilan17 to produce an example of multiple resource constraints

**Comment by martaguti** [comment]
Updated an initial proposal , containing :
- reference to rules for global exchange 
- set of generic checks for all records

**Comment by amilan17** [comment]
Examples of repeatable resourceConstraint elements from the NCEI Metadata Template. 
```

<gmd:resourceConstraints xlink:title="Distribution Liability">
	<gmd:MD_LegalConstraints>
		<gmd:accessConstraints>
			<gmd:MD_RestrictionCode codeList="https://data.noaa.gov/resources/iso19139/schema/resources/Codelist/gmxCodelists.xml#MD_RestrictionCode" codeListValue="otherRestrictions"> otherRestrictions </gmd:MD_RestrictionCode>
		</gmd:accessConstraints>
		<gmd:otherConstraints>
			<gco:CharacterString> Distribution liability: NOAA and NCEI make no warranty, expressed or implied, regarding these data, nor does the fact of distribution constitute such a warranty. NOAA and NCEI cannot assume liability for any damages caused by any errors or omissions in these data. If appropriate, NCEI can only certify that the data it distributes are an authentic copy of the records that were accepted for inclusion in the NCEI archives. </gco:CharacterString>
		</gmd:otherConstraints>
	</gmd:MD_LegalConstraints>
</gmd:resourceConstraints>
<gmd:resourceConstraints xlink:title="Use Liability">
	<gmd:MD_LegalConstraints>
		<gmd:useConstraints>
			<gmd:MD_RestrictionCode codeList="https://data.noaa.gov/resources/iso19139/schema/resources/Codelist/gmxCodelists.xml#MD_RestrictionCode" codeListValue="otherRestrictions"> otherRestrictions </gmd:MD_RestrictionCode>
		</gmd:useConstraints>
		<gmd:otherConstraints>
			<gco:CharacterString> Use liability: NOAA and NCEI cannot provide any warranty as to the accuracy, reliability, or completeness of furnished data. Users assume responsibility to determine the usability of these data. The user is responsible for the results of any application of this data for other than its intended purpose. </gco:CharacterString>
		</gmd:otherConstraints>
	</gmd:MD_LegalConstraints>
</gmd:resourceConstraints>
<gmd:resourceConstraints xlink:title="NCEI Data Citation Statement">
	<gmd:MD_LegalConstraints>
		<gmd:useLimitation>
			<gmd:MD_RestrictionCode codeList="https://data.noaa.gov/resources/iso19139/schema/resources/Codelist/gmxCodelists.xml#MD_RestrictionCode" codeListValue="otherRestrictions">otherRestrictions</gmd:MD_RestrictionCode>
		</gmd:useLimitation>
		<gmd:otherConstraints>
			<gco:CharacterString>Cite as: {{Last, F. M., F. M. Last, and F. M. Last}}. {{YYYY}}. {{Title}}. {{Version}}. [indicate subset used]. NOAA National Centers for Environmental Information. https://doi.org/{{DOI}}. Accessed [date]. </gco:CharacterString>
		</gmd:otherConstraints>
	</gmd:MD_LegalConstraints>
</gmd:resourceConstraints>
```

**Comment by martaguti** [comment]
Hi @amilan17 ,
That's an interesting use case of multiple resourceConstraints. Could you express the same idea by putting everything in one block of resourceConstraints?

**Comment by martaguti** [comment]
In the last TelCo we brought the discussion about whether every record should implement WMO_DatalicenceCode

Below is an example of Year of Polar Prediction (YOPP) dataset under a Creative Commons Attribution License

....
<gmd:resourceConstraints>
  <gmd:MD_LegalConstraints>
    <gmd:useLimitation>
      <gco:CharacterString>This work is licensed under the Creative Commons Attribution 3.0 License (URL: https://creativecommons.org/licenses/by/3.0/)</gco:CharacterString>
    </gmd:useLimitation>
    <gmd:useConstraints>
      <gmd:MD_RestrictionCode codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/Codelist/gmxCodelists.xml#MD_RestrictionCode" codeListValue="license">license</gmd:MD_RestrictionCode>
    </gmd:useConstraints>
    <gmd:otherConstraints>
      <gmx:Anchor xlink:href="https://creativecommons.org/licenses/by/3.0/">CC BY 3.0</gmx:Anchor>
    </gmd:otherConstraints>
  </gmd:MD_LegalConstraints>
</gmd:resourceConstraints>
....

Should we recommend instead the implementation of WMOOther e.g.

....
<gmd:resourceConstraints>
  <gmd:MD_LegalConstraints>
    <gmd:useLimitation>
      <gco:CharacterString>This work is licensed under the Creative Commons Attribution 3.0 License </gco:CharacterString>
    </gmd:useLimitation>
    <gmd:accessConstraints>
      <gmd:MD_RestrictionCode codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/Codelist/gmxCodelists.xml#MD_RestrictionCode" codeListValue="otherRestrictions">otherRestrictions</gmd:MD_RestrictionCode>
    </gmd:accessConstraints>
    <gmd:useConstraints>
      <gmd:MD_RestrictionCode codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/Codelist/gmxCodelists.xml#MD_RestrictionCode" codeListValue="otherRestrictions">otherRestrictions</gmd:MD_RestrictionCode>
    </gmd:useConstraints>
    <gmd:otherConstraints>
      <gmx:Anchor xlink:href="xlink:href="http://wis.wmo.int/2013/codelists/WMOCodeLists.xml#WMO_DataLicenseCode_WMOOther">WMOOther</gmx:Anchor>
    </gmd:otherConstraints>
    <gmd:otherConstraints>
      <gmx:Anchor xlink:href="https://creativecommons.org/licenses/by/3.0/">CC BY 3.0</gmx:Anchor>
    </gmd:otherConstraints>
  </gmd:MD_LegalConstraints>
</gmd:resourceConstraints>
....

**Comment by amilan17** [comment]
@martaguti - It is valid ISO to put everything into one one resourceConstraints block and I believe that the same ideas can expressed, because these statements are prefaced with 'Distribution Liability' and 'Use Liability'.

**Comment by josusky** [comment]
@martaguti you have there a minor typo, a repeated "xlink:href":
>  <gmx:Anchor xlink:href="xlink:href="http://wis.wmo.int/...

However, the more problematic in my opinions is the use of **WMOOther** that has a special meaning - it presents some kind of restriction (it covers for example OPMET data). And that restriction, if I am not mistaken, is not compatible with Creative Commons Attribution License.
The original definition seems quite OK to me - if the intention was to tell that the data usage shall respect a specific license (in this case a permissive one) that does not match any of traditional WMO/GTS limitations.

**Comment by martaguti** [comment]
Hi @josusky,

Thanks for spotting the typo, I've fixed it now. 
The presence of WMOOther for metadata records that are not Essential / Additional or No limitations was discussed in the last TelCo.
Or in other words do the records need to have always one of the codes from WMO_DataLicenceCode?

@gaubert or @kateroberts  mentioned they would look back on previous discussions.

I found the following report , it is old though 2013 .  Decisions 1, 10 and 11 refer to the topic.

[TT-ApMD-2-FinalReport.docx](https://github.com/wmo-im/wmcp/files/4103032/TT-ApMD-2-FinalReport.docx)

**Comment by gaubert** [comment]
Hi @martaguti @josusky @amilan17 

The conclusion of the report you mentionned Marta are correct from my understand. If you look at decision 10 and 11. WMOOther should be included if you want to make data policies that is not WMO Additional or Essential applicable in the WMO communities. This is what is implemented for instance by EUMETSAT for our DCPC products. Products that are not qualified by WMO Additional or Essential and available via the GISCs.

This is here an example of a metadata record with have:

**Comment by martaguti** [comment]
Hi @wmo-im/tt-wismd,

Please review Data Policy KPI. I have entered a possible score and adapted to the new format.
https://github.com/wmo-im/wcmp/blob/KPI-K/KPI/K.adoc

I haven't sent a pull request to master yet as it would be nice to get consensus on scoring. 

Talk soon

**Comment by tomkralidis** [comment]
Thanks @martaguti , this is great work.  Agree on needing to discuss scoring (see #71) tomorrow.

**Comment by tomkralidis** [comment]
Implemented in https://github.com/wmo-im/wcmp/pull/80
