### ISSUE TITLE
Define KPI M Presence of a station identifier

### ISSUE THREAD

**Issue by efucile** [wmo-im/wcmp#29]

**Comment by efucile** [comment]
working on this branch https://github.com/wmo-im/wmcp/blob/KPI-M/KPI/M.adoc

**Comment by efucile** [comment]
merge with #20

**Comment by tomkralidis** [comment]
KPI created in https://github.com/wmo-im/wcmp/blob/KPI-D/KPI/D.adoc and is pending review/approval.
