### ISSUE TITLE
WMCP Migration to ISO-19115-3

### ISSUE THREAD

**Issue by efucile** [wmo-im/wcmp#3]
1. scope of activities needed:
- Based on drivers: additional content that would be newly highlighted in a revision of the WMCP
- Benefits of 19115-3
- Mapping from 19115:2003 to 19115-3 (2016/8)
- Other dependencies ?

2. Development of document setting out background, drivers, issues #5 
3. Assessment of GISCs capacity to handle full 19115:20113 records
4. Assessment of issues/ needs, for GISCs to handle current and new 19115, and services metadata

**Comment by katerobertsfreeman** [comment]
https://github.com/wmo-im/wmcp/issues/6 Benefits of 19115-3
https://github.com/wmo-im/wmcp/issues/5 Develop paper

**Comment by tomkralidis** [comment]
TT-WISMD 2021-04-09: as per the following [action](https://github.com/wmo-im/wcmp/wiki/Meeting-2021-04-09#actions):

>> to close all the issues regarding 19115-3, and to open a ticket to help choose the next version of metadata, also need to think about the migration tool, documentation.

Closing in lieu of #101
