### ISSUE TITLE
Define the authoritative iso 19139 file that should be used.

### ISSUE THREAD

**Issue by gaubert** [wmo-im/wcmp#30]
The one that is in http://wis.wmo.int is not the official reference. 
Assess the consequences if we change (migration effort)

**Comment by josusky** [comment]
Here is
what the WMO publication 1060 says about that:
"WMO hosts a copy of the ISO/TS 19139:2007 XML schemas at:
http://wis.wmo.int/2011/schemata/iso19139_2007/
schema/. The directory structure in which the XML schemata are published
mirrors that of the normative XML schema repository published by ISO at:
http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/.
For example, gmd.xsd can be found at
http://wis.wmo.int/2011/schemata/iso19139_2007/schema/gmd/gmd.xsd."

**Comment by amilan17** [comment]
xsi:schemaLocation="http://www.isotc211.org/2005/gmd https://wis.wmo.int/2013/schemata/iso19139_2007/schema.xsd"

**Comment by amilan17** [comment]
I get multiple errors, when I try to validate with http://wis.wmo.int/2011/schemata/iso19139_2007/schema/gmd/gmd.xsd. 

This is one example of the errors: "System ID: https://wis.wmo.int/2011/schemata/iso19139_2007/schema/gmd/metadataApplication.xsd
Engine name: Xerces
Severity: error
Description: A schema cannot contain two global components with the same name; this schema contains two occurrences of 'http://www.isotc211.org/2005/gmd,DS_Initiative'. "

**Comment by amilan17** [comment]
- 6.1.1. Each WIS Discovery metadata record shall validate without error against the XML Schemas defined in ISO/TS 19139:2007. 
-- From Part 1. WMCP v1.3 specification: Conformance Requirements

In the notes of this section, it suggests using the schemas hosted https://wis.wmo.int/2011/schemata/19139_2007/schema/, but it doesn't explicitly require validation against this copy of the schema. Also, there are 3 copies of the schema hosted at this site in year 2011, 2012 and 2013. 

**Recommendation for Review**
I recommend updating this guidance to state that in order to comply with 6.1.1 that the record must be validated by this version of the schema: https://wis.wmo.int/2013/schemata/iso19139_2007/schema.xsd

**Comment by gaubert** [comment]
Hi @amilan17 , many thanks, I could not find if in your note if https://wis.wmo.int/2013/schemata/iso19139_2007/schema.xsd is valid. It is a workable schema ? 

Another question, during the meeting, we said that we could use the official schema hosted by ISO itself because the WMCP only redefines or extend codelists. Is it possible and if yes, why should we use a copy of the schema hosted on the WMO website. I am not quite sure anymore if you already gave an answer.

**Comment by amilan17** [comment]
Hi @gaubert  - the WMO instance listed above is a workable schema.  
It looks like ISO doesn't host schemas for deprecated standards. 
https://standards.iso.org/iso/19115

**Comment by amilan17** [comment]
Found them: http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/.

**Comment by gaubert** [comment]
@amilan17 ok we need to bring that point during the meeting then tomorrow to finalize the task.

**Comment by tomkralidis** [comment]
We have typically used https://www.isotc211.org/2005/gmd/metadataEntity.xsd.  Having said this, it would be valuable to know the difference between it and https://www.isotc211.org/2005/gmd/metadataEntity.xsd (which is normative?).

**Comment by tomkralidis** [comment]
Update: at today's TT-WISMD meeting, we concluded that this issue is critical path to complete the KPIs as well as update documentaion and codelist XML. @amilan17 to research/confirm/assert.

**Comment by amilan17** [comment]
*   The best authoritative ISO schema to reference is at: https://schemas.isotc211.org/schemas/19139/ 
*   The authoritative ISO schema hosted by WMO is at: https://wis.wmo.int/index.php?dir=/2013/schemata/iso19139_2007

**Comment by amilan17** [comment]
**ISO**

```
<gmd:MD_Metadata xmlns:gmd="http://www.isotc211.org/2005/gmd"
                 xmlns:gco="http://www.isotc211.org/2005/gco"
                 xmlns:xlink="http://www.w3.org/1999/xlink"
                 xmlns:gmx="http://www.isotc211.org/2005/gmx"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xmlns:gts="http://www.isotc211.org/2005/gts"
                 xmlns:gml="http://www.opengis.net/gml/3.2"
                 xmlns:geonet="http://www.fao.org/geonetwork"
                 xsi:schemaLocation="http://www.isotc211.org/2005/gmd https://schemas.isotc211.org/schemas/19139/-/gmd/1.0/gmd.xsd http://www.isotc211.org/2005/gmx  https://schemas.isotc211.org/schemas/19139/-/gmx/1.0/gmx.xsd">
```

**Comment by amilan17** [comment]
**WMO**

```
<gmd:MD_Metadata xmlns:gmd="http://www.isotc211.org/2005/gmd"
   xmlns:gco="http://www.isotc211.org/2005/gco"
   xmlns:xlink="http://www.w3.org/1999/xlink"
   xmlns:gmx="http://www.isotc211.org/2005/gmx"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xmlns:gts="http://www.isotc211.org/2005/gts"
   xmlns:gml="http://www.opengis.net/gml/3.2"
   xmlns:geonet="http://www.fao.org/geonetwork"
   xsi:schemaLocation="http://www.isotc211.org/2005/gmd http://wis.wmo.int/2013/schemata/iso19139_2007/schema.xsd">
```

**Comment by amilan17** [comment]
**OLDER WMO** 

```
<gmd:MD_Metadata xmlns:gmd="http://www.isotc211.org/2005/gmd"
                 xmlns:gco="http://www.isotc211.org/2005/gco"
                 xmlns:xlink="http://www.w3.org/1999/xlink"
                 xmlns:gmx="http://www.isotc211.org/2005/gmx"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xmlns:gts="http://www.isotc211.org/2005/gts"
                 xmlns:gml="http://www.opengis.net/gml/3.2"
                 xmlns:geonet="http://www.fao.org/geonetwork"
                 xsi:schemaLocation="http://www.isotc211.org/2005/gmd   http://wis.wmo.int/2011/schemata/iso19139_2007/schema/gmd/gmd.xsd http://www.isotc211.org/2005/gmx  http://wis.wmo.int/2011/schemata/iso19139_2007/schema/gmx/gmx.xsd">
```

**Comment by amilan17** [comment]
The /templates/WCMPv1.3\_OPTandMAND-Example.xml file schema validates with all 3 options above.

**Comment by amilan17** [comment]
*   **ISO CodeLists:** https://schemas.isotc211.org/schemas/19139/resources/gmxCodelists.xml
*   **WMO CodeLists (2012):** https://wis.wmo.int/2012/codelists/WMOCodeLists.xml
*   **WMO Codeslists (2013)**: does not exist

**Comment by amilan17** [comment]
We should not remove previous versions of the ISO schema hosted by WMO, but moving forward, I think we should 

1.  always refer to the schema hosted by ISO
2.  only host WMO defined resources (codes and WMO validators), instead of the whole schema
3.  Support all options for validation

**Comment by josusky** [comment]
@amilan17  I have asked this in other issue, but perhaps this is a more appropriate place. The two WMO CodeLists versions (2012 and 2013) are exactly equal. I can see that metadata documents from certain providers refer to 2012 and from others to 2013 (some even to 2010 but that is another story). Now is it intentional that the 2012 and 2013 versions are equal? Should we prefer (require) specific version or should we accept both?
It is mainly issue for automated tools (validators), that need tweaking to accept such duality.

**Comment by amilan17** [comment]
@tomkralidis - I think this is no longer relevant. Please close as you see fit.
