### ISSUE TITLE
Organise KPIs based on the categories from NOAA rubric

### ISSUE THREAD

**Issue by efucile** [wmo-im/wcmp#37]

**Comment by efucile** [comment]
@amilan17 to add links, examples and info on NOAA rubric

**Comment by amilan17** [comment]
- Example Rubric Result: https://data.noaa.gov/metaview/page?xml=NOAA/NESDIS/NGDC/MGG/DEM//iso/xml/258.xml&view=rubricv2/recordHTML&header=none
- URL to XSL: https://data.noaa.gov/metaview/views/rubricv2/recordHTML.xsl

**Comment by amilan17** [comment]
More information about the Rubric: https://www.ngdc.noaa.gov/wiki/index.php/Completeness_Rubric

The categories in the NOAA Rubric are: 

1. Identification
2. Access
3. Coverage
4. Content
5. History
6. Quality
7. Connection
8. Metadata
9. Associated Resources

**Comment by tomkralidis** [comment]
Closing given #53 implementation into pywcmp.
