### ISSUE TITLE
implement WCMP validator via pywcmp

### ISSUE THREAD

**Issue by efucile** [wmo-im/wcmp#43]
[pywcmp](https://github.com/wmo-im/pywcmp) was initially implemented in 2013 as part of MSC DCPC requirements or WMO WIS.  Update pywcmp functionality as per below:

Features:
- [x] composable: can be used as a library by a downstream Python application or command line tooling
- [x] implements ATS
- [x] implements KPIs
- [x] implements scoring rubric

**Comment by tomkralidis** [comment]
I've updated this issue a bit now that we are ready to implement the KPIs.  Please see checklist above and feel free to update as desired.

**Comment by tomkralidis** [comment]
FYI KPI implementation started at https://github.com/wmo-im/pywcmp/issues/17 cc @wmo-im/tt-wismd

**Comment by tomkralidis** [comment]
KPI implementation and scoring rubric implemented.  Closing given initial implementation of original scope of ticket is complete.
