### ISSUE TITLE
Subset of catalogue record to be downloaded and copied in the github repository

### ISSUE THREAD

**Issue by efucile** [wmo-im/wcmp#45]

**Comment by martaguti** [comment]
Hi @jkorosi   Jan (new) 
Jan Osusky agreed to take care of this issue, I believe .  Let me know if not
 @efucile  you still need to add Jan Osusky to the group, he doesn't show up as a user to assign tickets.  
Jan (new) do you know what's J.Osusky user id in github? 

We agreed that a representative set of xml records could be extracted from the downloaded set from the GISC at DWD an uploaded to github

Marta

**Comment by efucile** [comment]
I just invited Jan Osusky using his email.

**Comment by jkorosi** [comment]
Here is a set of examples. Please take a look if they are representative enought.
[WIS-CAT-Examples.zip](https://github.com/wmo-im/wmcp/files/4103064/WIS-CAT-Examples.zip)

**Comment by tomkralidis** [comment]
cc @josusky 

Not sure of the scope/purpose of this ticket. Note that we have nightly bundles available at https://github.com/wmo-im/wcmp/wiki/WISMetadataCatalogue, we should clarify whether we need to keep subsets in GitHub.

Thoughts?  Should we close or further investigate/clarify?

**Comment by josusky** [comment]
The idea here was to create a representative sub-set. But as the catalogue changes, this sub-set gets outdated. I think that we do not need to maintain our own sub-set as we are already running tools on top of the whole catalogue.
