### ISSUE TITLE
Provide list of mandatory elements

### ISSUE THREAD

**Issue by efucile** [wmo-im/wcmp#48]
Find a list of mandatory elements and use them as a metric in the Performance Indicator. For example, the DataDistributionScope (GlobalExchange, RegionalExchange, OriginatingCenter) is crucial to the WIS Core Cache

**Comment by hermannasensio** [comment]
this means e.g. to specify the mandatory descriptiveKeywords for WMO Core Profile 1.3

**Comment by hermannasensio** [comment]
two examples, chapters see Guide on Wis (2017 edition), Part V 
- 5.8.1.8.2 WMO_DistributionScopeCode keywords
- 5.8.1.10 Data policy information

**Comment by josusky** [comment]
Isn't this covered by the [KPI-9](https://github.com/wmo-im/wcmp/blob/master/kpi/009-data-policy.adoc)?

**Comment by tomkralidis** [comment]
Correct @josusky, closing given the KPI implementation.
