### ISSUE TITLE
Add support for ISO 19119 - "Geographic information — Services"

### ISSUE THREAD

**Issue by efucile** [wmo-im/wcmp#49]
D.	WMO Core Profile 1.3 is derived from the ISO 19139 XML representation of ISO 19115 "Geographic Information — Metadata"
Support should be added for ISO 19119 - "Geographic information — Services" to support Web Services such as Web Feature Service (WFS)/ Web Coverage Service (WCS) / Web Map Service (WMS) and others. Example xml files are attached

[de.dwd.cdc.services.txt](https://github.com/wmo-im/wmcp/files/3896400/de.dwd.cdc.services.txt)
[de.dwd.services.wfs.txt](https://github.com/wmo-im/wmcp/files/3896401/de.dwd.services.wfs.txt)

**Comment by amilan17** [comment]
We are not updating WCMP 1.3.
