### ISSUE TITLE
WIS Catalogue statistics

### ISSUE THREAD

**Issue by jkorosi** [wmo-im/wcmp#51]
Dear all,
I created a set of tool/test in the attached file "testWISCatalog.py" and ran it over the whole WIS catalogue (DWD GISC snapshot from 18 November 2019).

**WMO Rubric Records**
 I did a conversion of the whole catalogue by [http://www.ngdc.noaa.gov/metadata/published/xsl/wmoRubricReport.xsl](http://www.ngdc.noaa.gov/metadata/published/xsl/wmoRubricReport.xsl) and extracted _**WMO Profile 1.3 Score**_. I did it because I hope it would help me to identify good entries for _https://github.com/wmo-im/wmcp/issues/45_.
For this, you can use **_wmoRubric_** and **_wmoRubricScore_** commands.
Summary:
- There are 102827 entries in total
- highest possible score is 14/22 ("Encoding Compliance" and "Global Exchange Compliance " are just empty rules) 

 | entries | % | Score |
 | --------: | ---: | ----------------- |
 | 13397  | 13%  | 14/22  |
 | 6322  | 6.1%  |  13/22  |
 | 2465  | 2.4% |  12/22  |
 | 1608  | 1.6%  |  11/22 |
 | 25459  | 24.8%  |  10/22 |
 | 1428  | 1.4%  |  9/22 |
 | 52140 | 50.7% |  8/22 |
 | 8  | 0.0%  |  7/22 |

**Statistic over constrains**
The "dir" and "files" tests check the presence of following elements defined by XPath:
- //gmd:descriptiveKeywords[gmd:MD_Keywords/gmd:type/gmd:MD_KeywordTypeCode- /text()="dataCentre"]/gmd:MD_Keywords/gmd:keyword/gco:CharacterString/text()
- //gmd:resourceConstraints/gmd:MD_Constraints/gmd:useLimitation/gco:CharacterString/text()
- //gmd:resourceConstraints/gmd:MD_LegalConstraints/gmd:accessConstraints/gmd:MD_RestrictionCode/text()
- //gmd:resourceConstraints/gmd:MD_LegalConstraints/gmd:useConstraints/gmd:MD_RestrictionCode/text()
- //gmd:resourceConstraints/gmd:MD_LegalConstraints/gmd:otherConstraints/gco:CharacterString/text()
in element
- /gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification
The result is **xpathStatDir.csv** where you can apply filter in e.g. Excel for closer analysis.
During this analysis, I found the following issues:

_**Identified issues:**_

1. There are 29933 entries (from 102827) which use default namespace for gmd. It conflicts with:
    `6.2.1 Each WIS discovery metadata record shall name explicitly all namespaces used within the record: use of default namespaces is prohibited.`
Some of such entries define **gmd** namespace as a default namespace,  and in addition, also by **gmd** prefix. I guess they are generated automatically.
2. There are 718 entries which don't define all namespaces used in XML document.

**Entries duplicity**
During the testing, we realized that there are a lot of entries which differ only by time, or station they are related.

1. 346 entries which start with "METOP-A.GOME2.L3.O3.VCD.NRT.GDP-4.", differ by the datetime. 
2. 2980 entries which start with "de.dwd.mosmix." differ only by the related location
3. A lot of entries are not well formtted, e.g. entries which start with "de.pangaea.dataset." Humans need to use formatting tool for reading, comparing, ... Maybe it should be at least some recommendation to format it.

I know that these duplicities are sometimes necessary, but it seems to me that sometimes they are not. We are going to define KPI to check only a particular entry, but maybe it will be useful to define also KPI which will test one entry against the rest of the catalogue.
I started to write a command "compare" which should compare entries by content. First attempt was to group them by name prefixes. But this is not such a straightforward approach. Maybe some brute force algorithm for comparing all files should be used for this. But I am not sure if my thoughts about it are right. The intention is to "tidy up" WIS catalogue. What do you think?

I wish you a Merry Christmas.
Jan

**Comment by jkorosi** [comment]
[wis-catalog-stat.zip](https://github.com/wmo-im/wmcp/files/3989513/wis-catalog-stat.zip)

**Comment by martaguti** [comment]
Hi @jkorosi ,
The stats are very useful.
With a pivot table on the csv file provided, I checked all the different combinations of entries for data policy and distribution scope that the records on the wis have at present. There's all kinds ...

Maybe we can discuss it on Thursday telCo. 

Useful to pick up all the records making use of default namespace as that can break UI's.
Is that something the the rubric checks ? If not , it should be for sure a KPI

**Comment by josusky** [comment]
Statistics obtained using **pywmcp** tool:
Total number of tested records: 102814 
Success (no issue found):  9839 (9,6%)

Rule | Failed MD | [%] | Description
6.1.1 | 0 | 0,0% | xml-schema-validation
6.1.2 | 0 | 0,0% | Rule-based-validation – not implemented
6.2.1 | 29918 | 29,1% | Namespace-identification (no default ns)
6.3.1 | 32823 | 31,9% | Namespace-specification
8.1.1 | 0 | 0,0% | FileIdentifier-cardinality
8.2.1 | 80380 | 78,2% | Keyword-cardinality
8.2.2 | 79890 | 77,7% | Keyword-theme
8.2.3 | 81607 | 79,4% | Keyword-grouping
8.2.4 | 36 | 0,0% | bouding box
9.1.1 | 3780 | 3,7% | Identification-of-globally-exchanged-data
9.2.1 | 43555 | 42,4% | FileIdentifier-for-globally-exchanged-data
9.3.1 | 52733 | 51,3% | WMO-data-policy-for-globally-exchanged-data
9.3.2 | 81749 | 79,5% | GTS-priority-for-globally-exchanged-data

**Comment by tomkralidis** [comment]
cc @josusky 

Re-opening.  Since pywcmp reports on a metadata record basis, pywiscat is the suitable place to be able to run pywcmp and provide higher level reporting (by GISC, country, overall, etc.)

**Comment by josusky** [comment]
OK, I think we should create an issue in *pywiscat* to add _pywcmp_ into "requirements.txt" and consequently do the integration. Well, we might end up needing some adjustments here in *pywcmp* too, but the driver should be the *pywiscat*, I guess.

**Comment by amilan17** [comment]
@tomkralidis  - I think this can be closed?
