### ISSUE TITLE
Proposal for a WMO Metadata quality KPI Scoring

### ISSUE THREAD

**Issue by gaubert** [wmo-im/wcmp#53]
# Proposal for a WMO Metadata quality KPI Scoring

The following issue summarizes a first draft proposal for providing a scoring algorithm for qualifying each individual metadata records (or information provided regarding the product information content).

This scoring mechanism is greatly inspired by the NOAA rubric ([https://data.noaa.gov/metaview/page?xml=NOAA/NESDIS/NCDC/Geoportal//iso/xml/C00589.xml&view=rubricv2/recordHTML&header=none](https://data.noaa.gov/metaview/page?xml=NOAA/NESDIS/NCDC/Geoportal//iso/xml/C00589.xml&view=rubricv2/recordHTML&header=none)) and the Qualys SSL Labs "SSL Certificate" evaluation scoring explained here: [https://github.com/ssllabs/research/wiki/SSL-Server-Rating-Guide](https://github.com/ssllabs/research/wiki/SSL-Server-Rating-Guide)

Results of an evaluation page can be checked here: 

[https://www.ssllabs.com/ssltest/index.html](https://www.ssllabs.com/ssltest/index.html)

## KPI Types

Within the discussion and creation of KPIs and looking at other scoring engines for metadata quality 3 categories of KPIs are emerging:

* **Mandatory**: It regroups all the rules that are necessary to comply to a WMO Core Profile 1.3 (compliance to Metadata schema and compliance to additional rules)

* **Required**: That category regroups all the additional KPIs (the ones currently defined by TT-WMD) that have been judged necessary to create a meaningful metadata record

* **Recommended**: this category is an optional category that is not required but makes a metadata record standing out of the rest of the record

## Overall score mechanism

Following the Qualys labs, a two levels strategy can be adopted to evaluate a metadata record.

The overall score can be between 0 and 100 and mapped to a letter grade (A, B, C ,D) with the following translation table.

**Letter grade translation**

<table>
  <tr>
    <td>Numerical Score</td>
    <td>Grade</td>
  </tr>
  <tr>
    <td>score >= 80</td>
    <td>A</td>
  </tr>
  <tr>
    <td>score >= 65</td>
    <td>B</td>
  </tr>
  <tr>
    <td>score >= 50</td>
    <td>C</td>
  </tr>
  <tr>
    <td>score >= 35</td>
    <td>D</td>
  </tr>
  <tr>
    <td>score >= 20</td>
    <td>E</td>
  </tr>
  <tr>
    <td>score < 20</td>
    <td>F</td>
  </tr>
</table>

This score will be calculated only if the metadata is compliant to WMO Core profile 1.3. If not compliant a special Letter (U like uncompliant) should be provided.

### Score computation

To compute the overall score over 100, the different KPIs are split in categories:

Here is an initial proposal of the categories:

* Identification Info (Title Abstract)

* Coverage (temporal geographical)

* Distribution information 

    * Formats

* Data Policy

* Enhancements

    * Broken links

    * Graphic Overview

Inside each category, there will be required and recommended KPIs. A 0 score for a required KPI brings a 0 in the complete category.

For instance, a 0 in the Title KPI would give the IdentificationInfo category a 0.

Then each category will receive a weighted value. For instance (numbers are to be defined).

 

<table>
  <tr>
    <td>Category</td>
    <td>Score</td>
    <td>Example of score for metadata</td>
  </tr>
  <tr>
    <td>C1 Identification Info </td>
    <td>20%</td>
    <td>85 over 100</td>
  </tr>
  <tr>
    <td>C2 Coverage</td>
    <td>25%</td>
    <td>75 over 100</td>
  </tr>
  <tr>
    <td>C3 Distribution Information</td>
    <td>25%</td>
    <td>55 over 100</td>
  </tr>
  <tr>
    <td>C4 Data Policy</td>
    <td>15%</td>
    <td>45 over 100</td>
  </tr>
  <tr>
    <td>C5 Enhancements</td>
    <td>15%</td>
    <td>65 over 100</td>
  </tr>
</table>

 

Formula pending the overall scoring contribution is over 100 and the individual category scores are over 100:

(C1x0.2) + (C2x0.25)+(C3x0.25)+(C4x0.15)+(C5x0.15) = 66 % that would be B.

### Individual Categorie Scoring

A category should contain multiple KPIs tests and should return a score over 100.

There are different strategies that can be applied: a ponderation similar applied to make the overall score:

Category A:

* KPI 1    50%

* KPI 2    25%

* KPI3     25%

Or in the case that some of the KPIs results should be used or prevented it could impact the result.

For instance in the data policy, let’s imagine that only data policies with anchors are authorized but non anchor data policy are authorized for a transition period, and the metadata record contains both. 

* Anchor Data Policy = 100%

* Non Anchor Data Policy = 75 %

To define the total score, you can take the best way of encoding (anchor DP), add the non anchor DP score and divide by 2. 

### Non Compliance information

For each category and KPI, all individual errors should be presented: error title, show what XML element is evaluated and its value and then the value expected.

The NOAA rubric can be copied for that.

### Example of the Qualys SSL Test web site

![screencapture-ssllabs-ssltest-analyze-html-2020-01-23-13_47_51](https://user-images.githubusercontent.com/1482/72986591-cd0b5380-3de8-11ea-9a7e-5607b7139d9b.png)

**Comment by efucile** [comment]
During teleconference 23.1.2020 
- Anna. It may be too complex for our aims. 
- Marta. We need to consider the possibility to extend the scoring when adding more KPIs
- Tom. Extensibility is important and we can also consider that someone can add KPIs not of general interest.
- **Guillaume asks to provide categories for the existing KPIs.**

**Comment by gaubert** [comment]
@tomkralidis I have reviewed this proposal that I had written one year-ish ago and I would propose to keep quite a lot of things from it as they are still valid:

- creation of two types of KPIs scoring elements (Required and Recommended) 
This is to have a full-proof scoring mechanism that do not give the same weight to all scoring elements in a given KPI.
This to avoid having a KPI put as "green" because recommended elements are there but required are not.

For instance if we take the temporal KPI (E), below are the elements to score.
The first three are Required while the last two are Recommended. The metadata record is functional without the update frequency and the status defined. You could score 3 having the temporal extent, the update frequency and the status defined without having rule 2 and 3 implemented for instance.
In most cases, it will not be necessary to have recommended elements but the mechanism is there to implement it.

To implement it, we could ponder the recommended with a lower weight (1/2 for instance) or have a 2 scale system with a score and +++ for instance (3++ or A++ if we translate it to a letter).
 
Rule | Score
-- | --
The Temporal Extent is defined | 1
The Temporal Extent contains begin and end components | 1
The begin date time is less than or equal to the end date time | 1
The Data Update Frequency is defined | 1
The Data Status is defined | 1

Then in terms of presentation, I like the overall score associated with a colour (green to red) and translated to a letter because it simplifies greatly the usability and understanding of the score. You immediatly know if you scored well or not.

If necessary, meaning if the KPIs are not self-sufficient some can be regrouped in categories that are presented together (Data Policy, Spatial/Temporal coverages, product information, ....) . 
That could allow to create a very simple/high level dashboard.

You need to have the ability to drill down to an explanation of the issue if we can build it.

**Comment by josusky** [comment]
Just to be sure, the categories mentioned here such as "Identification Info (Title Abstract)" do they map to KPIs in "1 to n" manner, i.e. the aforementioned category would be KPI B + KPI C? I just want to be sure that defined KPIs are treated "atomically", i.e. that each KPI is fully in one category or another but not half here and half there.

**Comment by tomkralidis** [comment]
Update (TT-WISMD 2021-03-19): @gaubert will review the KPIs with @martaguti and others and prepare an implementation proposal (required, recommended, groupings).

**Comment by gaubert** [comment]
Ok I am waking up a bit late but I had a look at the different KPIs and only one could potentially contain required and recommended criteria/tests so I don't think it is necessary to complicate the final scoring algorithm for the moment.
Beside that we are calculating a percentage so if some criterias are less important we could ponder them when they are calculated.
In the end we will get an overall percentage that can allow defining the final grade (we could also ponder by giving more weight on some specific KPIs) like if the mandatory one fails you get a bad/average grade for instance. 

In terms of presentation, I would still propose to regroup in categories the KPIs as it will help to add more in the future and summarizes the information alongside the grade. It would also allow providing some pondering between the categories if necessary. Here is a proposal:

- Mandatory (How do we deal with it ?)
  * KPI-1: WCMP compliance
- Editorial Information (5/12)
    * KPI-2: Good Quality title
    * KPI-3: Good Quality abstract
    * KPI-6: Keywords Usage
    * KPI-7: Graphic Overview
    * KPI-12: DOI citation
- Coverage: (1/12)
   * KPI-4: Temporal Coverage
- Data Policy (2/12):
  * KPI-9: Data Policy
   * KPI-5: WMOEssential 
- Distribution Information (1/12):
  * KPI-10: Distribution Information
- Enhancements (technical elements) (2/12):
  * KPI-8: Links health
  * KPI-11:Codelists validation

To compute the grade A score we could use something like this:


Numerical Score | Grade
-- | --
score >= 80 | A
score >= 65 | B
score >= 50 | C
score >= 35 | D
score >= 20 | E
score < 20 | F

If the mandatory elements are not passed a special letter (U for uncompliant) could be used.

**Comment by tomkralidis** [comment]
Update (TT-WISMD 2021-04-09): expanding for all of @wmo-im/tt-wismd to provide feedback.  We will agree on the approach at our [next meeting](https://github.com/wmo-im/wcmp/wiki/Meeting-2021-05-07) and then implement in pywcmp.

**Comment by josusky** [comment]
I agree that it is useful to group the KPI checks.
Here is my version, based on Guillaume's proposal, with only 5 groups:
* Mandatory (1/12)
  * KPI-1: WCMP compliance
* Editorial Information (4/12)
  * KPI-2: Good Quality title
  * KPI-3: Good Quality abstract
  * KPI-6: Keywords Usage
  * KPI-12: DOI citation
* Content: (2/12) // a better name is welcomed
  * KPI-4: Temporal Coverage
  * KPI-9: Data Policy
* Distribution Information (2/12):
  * KPI-5: WMOEssential data links
  * KPI-10: Distribution Information
* Enhancements (technical elements) (3/12):
  * KPI-7: Graphic Overview
  * KPI-8: Links health
  * KPI-11: Codelists validation

**Comment by amilan17** [comment]
I recommend the following: 

*   rename Editorial Info ==> Content Info
*   Move KPI-4 to Content Info
*   move KPI-9 to Distribution
*   move KPI-7 to Content

**Comment by josusky** [comment]
OK, here is the updated proposal:
* Mandatory (1/12)
  * KPI-1: WCMP compliance
* Content Information (6/12)
  * KPI-2: Good Quality title
  * KPI-3: Good Quality abstract
  * KPI-4: Temporal Coverage
  * KPI-6: Keywords Usage
  * KPI-7: Graphic Overview
  * KPI-12: DOI citation
* Distribution Information (3/12):
  * KPI-5: WMOEssential data links
  * KPI-9: Data Policy
  * KPI-10: Distribution Information
* Enhancements (technical elements) (2/12):
  * KPI-8: Links health
  * KPI-11: Codelists validation
 
 Now in addition to the grouping itself, there is a question of the grouping functionality. Will we provide a sub-summary per group or not?

**Comment by tomkralidis** [comment]
Thanks @josusky.  Perhaps the grouping should then be the default output/response.  +1 to add a percentage per group.

**Comment by tomkralidis** [comment]
@wmo-im/tt-wismd as per our [meeting action on 2021-05-07](https://github.com/wmo-im/wcmp/wiki/Meeting-2021-05-07#actions), please review/comment on @josusky 's updated grouping in preparation for our [meeting on 2021-05-21](https://github.com/wmo-im/wcmp/wiki/Meeting-2021-05-21), thanks much in advance.

**Comment by tomkralidis** [comment]
Update 2021-05-21: 
- default output is existing
- pass `-g/--group` flag to group
- add total / score / percentage per group

**Comment by tomkralidis** [comment]
@wmo-im/tt-wismd grouping has now been implemented in pywcmp (in current master branch) for review and comment -- thanks @josusky!

Sample invocation:

```bash
pywcmp kpi validate --file foo.xml --group
```

Sample output:

```json
{
    "mandatory": {
        "kpi_001": {
            "name": "KPI-1: WCMP 1.3, Part 2 Compliance",
            "total": 13,
            "score": 13,
            "comments": [],
            "percentage": 100.0
        }
    },
    "content_information": {
        "kpi_002": {
            "name": "KPI-2: Good quality title",
            "total": 8,
            "score": 5,
            "comments": [
                "Line 207: title contains non-printable characters",
                "Line 207: title is not title case",
                "Line 207: title contains spelling errors ['gdps', 'longwave']"
            ],
            "percentage": 62.5
        },
        "kpi_003": {
            "name": "KPI-3: Good quality abstract",
            "total": 3,
            "score": 2,
            "comments": [
                "Line 252: contains spelling errors ['gdps']"
            ],
            "percentage": 66.667
        },
        "kpi_004": {
            "name": "KPI-4: Temporal information",
            "total": 5,
            "score": 5,
            "comments": [],
            "percentage": 100.0
        },
        "kpi_006": {
            "name": "KPI-6: Keywords",
            "total": 4,
            "score": 3,
            "comments": [
                "Found 14 keywords that are not gmx:Anchor but a bare character string"
            ],
            "percentage": 75.0
        },
        "kpi_007": {
            "name": "KPI-7: Graphic overview for non bulletins metadata records",
            "total": 0,
            "score": 0,
            "comments": [],
            "percentage": null
        },
        "kpi_012": {
            "name": "KPI-12: DOI citation",
            "total": 6,
            "score": 2,
            "comments": [
                "Line 504: citation should start with \"Cite as\" and have matching DOI",
                "Line 507: citation should start with \"Cite as\" and have matching DOI"
            ],
            "percentage": 33.333
        },
        "summary": {
            "total": 26,
            "score": 17,
            "comments": {
                "kpi_002": [
                    "Line 207: title contains non-printable characters",
                    "Line 207: title is not title case",
                    "Line 207: title contains spelling errors ['gdps', 'longwave']"
                ],
                "kpi_003": [
                    "Line 252: contains spelling errors ['gdps']"
                ],
                "kpi_006": [
                    "Found 14 keywords that are not gmx:Anchor but a bare character string"
                ],
                "kpi_012": [
                    "Line 504: citation should start with \"Cite as\" and have matching DOI",
                    "Line 507: citation should start with \"Cite as\" and have matching DOI"
                ]
            },
            "percentage": 65.385
        }
    },
    "distribution_information": {
        "kpi_005": {
            "name": "KPI-5: WMOEssential data links",
            "total": 1,
            "score": 1,
            "comments": [],
            "percentage": 100.0
        },
        "kpi_009": {
            "name": "KPI-9: Data policy",
            "total": 5,
            "score": 1,
            "comments": [
                "Line 504: WMO_DataLicenseCode is not defined as an anchor",
                "Legal constraint gmd:useConstraints not found",
                "No definition of the distribution scope found (keyword from WMO_DistributionScopeCode thesaurus)",
                "No product category code defined for globally or regionally exchanged data (keyword from WMO_GTSProductCategoryCode code list)"
            ],
            "percentage": 20.0
        },
        "kpi_010": {
            "name": "KPI-10: Distribution information",
            "total": 5,
            "score": 3,
            "comments": [
                "Distribution format not found (expected at //gmd:distributionInfo//gmd:distributionFormat/gmd:MD_Format)"
            ],
            "percentage": 60.0
        },
        "summary": {
            "total": 11,
            "score": 5,
            "comments": {
                "kpi_009": [
                    "Line 504: WMO_DataLicenseCode is not defined as an anchor",
                    "Legal constraint gmd:useConstraints not found",
                    "No definition of the distribution scope found (keyword from WMO_DistributionScopeCode thesaurus)",
                    "No product category code defined for globally or regionally exchanged data (keyword from WMO_GTSProductCategoryCode code list)"
                ],
                "kpi_010": [
                    "Distribution format not found (expected at //gmd:distributionInfo//gmd:distributionFormat/gmd:MD_Format)"
                ]
            },
            "percentage": 45.455
        }
    },
    "enhancements": {
        "kpi_008": {
            "name": "KPI-8: Links health",
            "total": 16,
            "score": 7,
            "comments": [
                "\"amqps://dd.weather.gc.ca/model_gem_global.#\" cannot be resolved!"
            ],
            "percentage": 43.75
        },
        "kpi_011": {
            "name": "KPI-11: Codelists validation",
            "total": 18,
            "score": 14,
            "comments": [
                "Line 304: Invalid codelist value: None not in MD_KeywordTypeCode",
                "Line 404: Invalid codelist value: None not in MD_KeywordTypeCode",
                "Line 430: Invalid codelist value: None not in MD_KeywordTypeCode",
                "Line 456: Invalid codelist value: None not in MD_KeywordTypeCode"
            ],
            "percentage": 77.778
        },
        "summary": {
            "total": 34,
            "score": 21,
            "comments": {
                "kpi_008": [
                    "\"amqps://dd.weather.gc.ca/model_gem_global.#\" cannot be resolved!"
                ],
                "kpi_011": [
                    "Line 304: Invalid codelist value: None not in MD_KeywordTypeCode",
                    "Line 404: Invalid codelist value: None not in MD_KeywordTypeCode",
                    "Line 430: Invalid codelist value: None not in MD_KeywordTypeCode",
                    "Line 456: Invalid codelist value: None not in MD_KeywordTypeCode"
                ]
            },
            "percentage": 61.765
        }
    },
    "summary": {
        "total": 84,
        "score": 56,
        "comments": {
            "kpi_002": [
                "Line 207: title contains non-printable characters",
                "Line 207: title is not title case",
                "Line 207: title contains spelling errors ['gdps', 'longwave']"
            ],
            "kpi_003": [
                "Line 252: contains spelling errors ['gdps']"
            ],
            "kpi_006": [
                "Found 14 keywords that are not gmx:Anchor but a bare character string"
            ],
            "kpi_008": [
                "\"amqps://dd.weather.gc.ca/model_gem_global.#\" cannot be resolved!"
            ],
            "kpi_009": [
                "Line 504: WMO_DataLicenseCode is not defined as an anchor",
                "Legal constraint gmd:useConstraints not found",
                "No definition of the distribution scope found (keyword from WMO_DistributionScopeCode thesaurus)",
                "No product category code defined for globally or regionally exchanged data (keyword from WMO_GTSProductCategoryCode code list)"
            ],
            "kpi_010": [
                "Distribution format not found (expected at //gmd:distributionInfo//gmd:distributionFormat/gmd:MD_Format)"
            ],
            "kpi_011": [
                "Line 304: Invalid codelist value: None not in MD_KeywordTypeCode",
                "Line 404: Invalid codelist value: None not in MD_KeywordTypeCode",
                "Line 430: Invalid codelist value: None not in MD_KeywordTypeCode",
                "Line 456: Invalid codelist value: None not in MD_KeywordTypeCode"
            ],
            "kpi_012": [
                "Line 504: citation should start with \"Cite as\" and have matching DOI",
                "Line 507: citation should start with \"Cite as\" and have matching DOI"
            ]
        },
        "percentage": 66.667,
        "identifier": [
            "urn:x-wmo:md:int.wmo.wis::c041e79a-914a-5a4e-a485-9cbc506195df-GDPS.ETA_AD"
        ],
        "grade": "B"
    }
}
```

**Comment by tomkralidis** [comment]
2021-06-04 TT-WISMD: @josusky provided a demo which was positively received and approved.

@gaubert with your +1, we can close this ticket.

**Comment by gaubert** [comment]
Looks good guys. Well done and congratulations. We can close it then.
