### ISSUE TITLE
Release strategy

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wcmp#58]
cc @wmo-im/tt-wismd for review and comment

**Summary and Purpose**
This repository contains numerous components that represent our deliverables:
- WMO Metadata Core Profile (document)
- codelists (ISO Codelist Catalogue, publish to codes.wmo.int)
- KPIs
- scoring rubric (documentation, scoring rubric [CSV?])
- other documentation

We need a release strategy to be able to version and release the above in an agile manner.

Note that tooling (which will implement the components here) is not scope for this repo.

**Proposal**
Options
1. provide a versioned release which represents all of the components above is tagged
2. split components into logical sub repos which have their own lifecycle
3. other options?

**Reason**
Initial options presented above for discussion.

**Comment by efucile** [comment]
I vote for 2 as these are very different things in need of their own lifecycle

**Comment by tomkralidis** [comment]
If we go with option 2 this would mean additional GitHub repositories foreach component.  Comments/objections?

**Comment by amilan17** [comment]
I think multiple repos will be better too.

**Comment by josusky** [comment]
I understand the view of Enrico and Anna. Managing multiple "products" in one repository is somewhat unusual. On the other hand, this repository is quite small and each deliverable has a separate folder. Im my opinion what matters here is whether we expect the releases of KPIs to interleave with releases of, let say, codelists. If yes, then separate repositories are needed. If not, i.e. if we will work on the deliverables sequentially, then the first option (one repo) if OK too.

**Comment by martaguti** [comment]
Hi ,
Do we need to do versioning of each of the deliveries to go in synch with git tags releases ?  If so we need different repos, right?  Not sure you can do different tag releases for subdirectories.

Are there dependencies between any of the components (as @josusky  mentions) so that they need to be together? 
are the rubrics/codelists dependent of the wmo core profile 1.3 documents

**Comment by tomkralidis** [comment]
I would imagine the codelists as being independent.  Once we release a version of the codelist, then the codelist is:
- publised to codes.wmo.int
- published as an ISO Codelist Catalogue XML document to something like `https://schemas.wmo.int/wis/metadata/codelists/<version>/WMOCodeLists.xml`
- then any metadata document can point to the verisoned codelist safely i.e.

```xml
     <gmd:CI_DateTypeCode codeList="http://schemas.wmo.int/wis/metadata/codelists/1.3.7/WMOCodeLists.xml#CI_DateTypeCode" codeListValue="reference" codeSpace="ISOTC211/19115">reference</gmd:CI_DateTypeCode>
```

So then we would create, say, https://github.com/wmo-im/wis-metadata-codelists.  Which would be quite small and quiet, but able to evolve independently as required.

I'm guessing the KPIs and rubric would have to be tied to the core profile itself.

Documentation, best practices, cookbooks would be their own separate repos.

cc @amilan17 / @efucile for thoughts as well.

Thoughts?

**Comment by amilan17** [comment]
As a reference, the Aviation Data group has multiple repositories: https://github.com/orgs/wmo-im/teams/tt-avdata/repositories.

**Comment by tomkralidis** [comment]
Updates following discussion with @amilan17 :
- all things WMO codelists moved to https://github.com/wmo-im/wcmp-codelists
- documentation/best practices TBD
- this repo remains for:
  - core specification
  - KPIs
  - rubric
