### ISSUE TITLE
clarify acronym of this repo

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wcmp#59]
Hi @wmo-im/tt-wismd experts: there exist the following acronyms is this repository to describe the WMO Core Metadata Profile:

- WMCP
- WCMP

```bash
$ grep -Ri WCMP *|wc -l
     111
$ grep -Ri WMCP *|wc -l
      40
```

We need to choose one and be consistent across this repository and beyond.

I propose **WCMP** given the actual standard reads "**W**MO **C**ore **M**etadata **P**rofile".  This will include renaming this repo (GitHub will do the auto redirects for links and forks/etc.).

What do folks think?  Looking forward to your input/feedback.

**Comment by efucile** [comment]
go for it!

**Comment by amilan17** [comment]
WCMP works for me

**Comment by tomkralidis** [comment]
Updated (@amilan17 will also rename https://github.com/wmo-im/pywmcp accordingly).

**Comment by tomkralidis** [comment]
Update: https://github.com/wmo-im/pywcmp also renamed.

**Comment by gaubert** [comment]
WCMP is fine with me.

**Comment by Amienshxq** [comment]
WCMP is good~
