### ISSUE TITLE
add HTTPS as criteria for valuable links to KPI J and/or L

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wcmp#66]
**Summary and Purpose**
HTTPS is increasingly becoming a requirement for numerous agencies as well as the [suggested protocol vs. HTTP](https://www.cloudflare.com/learning/ssl/why-use-https/).

KPIs J and L both deal with evaluating links in a WCMP document, however there is no measure on whether links are HTTP or HTTPS.

Having non-HTTPS links in a WCMP document often leads to mixed content errors in web applications deployed via HTTPS for example, and using AJAX/XHR design patterns.

**Proposal**
Options:
1. add additional points for HTTPS links
2. provide NO points for HTTP links
3. do nothing, demanding HTTPS in the KPIs is too strict
4. other options?

**Reason**
Providing guidance on HTTPS supports secure, authoritative and trustworthy links as part of WIS Metadata and WIS.

Assigned to @josusky however looking for feedback from all of @wmo-im/tt-wismd.

**Comment by gaubert** [comment]
Looks to be a really good idea to me. It can be evaluated also when the evaluation for the broken links is done.

**Comment by gaubert** [comment]
I have also added the following comment in the pull request of the broken links:

We should also add the SSL certificate trustworthiness in mix. A link without a trusted certificate is like a broken link these days.
Browsers and command line tools like curl/wget will refuse by default to access the content of a web site with an invalid certificate.
It is quite easy to check as the full certs chain should be valid and available.

What do you think ?

**Comment by tomkralidis** [comment]
+1 good idea @gaubert

**Comment by josusky** [comment]
OK, I will add link checking into the pywcmp tool. But I am a bit confused by the proposed scoring. I am looking at "https://github.com/wmo-im/wcmp/blob/KPI-J/KPI/J.adoc" and as far as I understand it, the metadata document needs at least 6 valid links to get max score. Is that the expected amount for all kind of products? I have checked "urn:x-wmo:md:int.wmo.wis::ISMD01EDZW" and there are only 4.

**Comment by tomkralidis** [comment]
Good point @josusky.  So then what about pure percentage (i.e. number of good links as a percentage of total links)? Let's cover in https://github.com/wmo-im/wcmp/pull/64#discussion_r528445997 ?  As well, I'll open another ticket for us to discuss KPI implementation in pywcmp.
