### ISSUE TITLE
KPI implementation checklist

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wcmp#68]
@wmo-im/tt-wismd : opening this issue to track overall progress on KPIs.  As each KPI branch is completed, we can check off the below.  Once the below is complete we can consider this the initial implementation to drive the scoring rubric and subsequent pywmcp implementation.

||KPI|contact|branch|PR|
|---|---|---|---|---|
|✅|A. Compliance to WMO Core Profile and its mandatory elements|@tomkralidis|[KPI-A](https://github.com/wmo-im/wcmp/tree/KPI-A)|#77|
|✅|B. Good quality title|@tomkralidis|[KPI-B](https://github.com/wmo-im/wcmp/tree/KPI-B)|#62|
|✅|C. Good quality abstract|@tomkralidis|[KPI-C](https://github.com/wmo-im/wcmp/tree/KPI-C)|#72|
|🚧|D. Valid Station Identifier and presence of a 'station identifier'|@tomkralidis|[KPI-D](https://github.com/wmo-im/wcmp/tree/KPI-D)|#83|
|✅|E. Temporal information (#21) |@gaubert|[KPI-E](https://github.com/wmo-im/wcmp/tree/https://github.com/wmo-im/wcmp/tree/KPI-E)|#79|
|✅|F. WMOEssential data links|@martaguti|[KPI-F](https://github.com/wmo-im/wcmp/tree/KPI-F)|#76|
|✅|~G. Bulletins have an ongoing temporal extent~|~@gaubert~|||
|✅|H. Well defined Keywords |@martaguti|[KPI-H](https://github.com/wmo-im/wcmp/tree/KPI-H)|#63|
|✅|I. GraphicOverview for non bulletins metadata records|@tomkralidis|[KPI-I](https://github.com/wmo-im/wcmp/tree/KPI-I)|#65|
|✅|J. Links health|@tomkralidis|[KPI-J](https://github.com/wmo-im/wcmp/tree/KPI-J)|#64|
|✅|K. Data Policy Possible combination|@martaguti|[KPI-K](https://github.com/wmo-im/wcmp/tree/KPI-K)|#80|
|✅|L. Distribution Info|@tomkralidis|[KPI-L](https://github.com/wmo-im/wcmp/tree/KPI-L)|#67|
|✅|M. Codelists validation|@martaguti|[KPI-M](https://github.com/wmo-im/wcmp/tree/KPI-M)|#86|
|✅|N. DOI citation information|@tomkralidis|[KPI-N](https://github.com/wmo-im/wcmp/tree/KPI-N)|#73|

**Comment by martaguti** [comment]
If M is a repeat of D, I propose to rename M to "Codelists validation"
which is something we discussed in  #35)

**Comment by tomkralidis** [comment]
Makes sense @martaguti .  I've updated #68 accordingly.  Are you able to tackle the new KPI M ?

**Comment by martaguti** [comment]
@tomkralidis yes I take M thanks

**Comment by tomkralidis** [comment]
Update:
- deferring KPI D for further discussion
- all other KPIs have been completed for the initial iteration

Great work all !!! 🎆 🎉
