### ISSUE TITLE
full review of KPI implementation

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wcmp#69]
@wmo-im/tt-wismd 

To review the entire KPI implementation (all KPIs, editorial consistency, link checking, formatting, etc.) once #68 is complete.

- [x] editorial consistency
- [x] link checking
- [x] verify correct/valid codelist URLs
- [x] formatting
- [x] consider updating the KPIs from alphabetical to some other scheme (A-Z will run out fast over time)
- [x] add introduction
  - [x] overview
  - [x] audience
  - [x] how to use
  - [x] reference implementation
- [x] s/wmcp/wcmp/i

**Comment by tomkralidis** [comment]
Note that we should provide an overview section as per @martaguti 's comments in https://github.com/wmo-im/wmcp/pull/63#discussion_r522938347

**Comment by tomkralidis** [comment]
Update from [2020-11-23 meeting](https://github.com/wmo-im/wmcp/wiki/Meeting-2020-11-23): we need an introductory section
- overview
- audience
- how to use
- reference implementation
- ...

**Comment by martaguti** [comment]
@tomkralidis  are we changing all references in the KPIs  from WMCP  to WCMP ?  as we have done with the repo ... (there's quite a few of those)

**Comment by tomkralidis** [comment]
@martaguti yes.  I've renamed things in master via 11e868066a20a5962b09ccc1c1932f95211b6756, but there are likely other areas in the older KPI branches.  Once we merge our first pass KPIs we can do another sweep.

**Comment by tomkralidis** [comment]
cc @josusky we should also do a full review of feasibility of implementation in [pywcmp](https://github.com/wmo-in/pywcmp).

**Comment by josusky** [comment]
I have impression that the "{counter:kpi}" does not seem to work. Is it only issue of my browser? When I open for example "https://github.com/wmo-im/wcmp/blob/issue-69/kpi/002.adoc" I see "KPI-1: Good quality title" but it should be "KPI-2 ...".

**Comment by tomkralidis** [comment]
@josusky the `{counter:kpi}` is not rendered by GitHub correctly, as it needs to be rendered by asciidoctor in generating an HTML or PDF file.  Depending on the next steps from WMO once we complete, we can review options.
