### ISSUE TITLE
add spell checking recommendations and options

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wcmp#75]
In KPI C (and perhaps others in the future) there are rules for implementation which require passing a spellchecker (English).

Provide recommendations and options on spell checking:
- dictionaries
- tools/services
- etc.

**Comment by Amienshxq** [comment]
@tomkralidis 
Hi tom,
I found two online dictionaries :  https://www.merriam-webster.com/  and   https://dictionary.cambridge.org/
The dictionary by Merriam-Webster is America's most trusted online dictionary for English word definitions, meanings.
The cambridge dictionary is more suitable for people whose native language is not English, it can translate English into many languages（French、German、Chinese、Japanese...）

And for the spell check & grammar check, I think this online tool might be appropriate: https://www.jspell.com/checker/
It's a free online spell checker and grammar checker, and it can mark out spelling mistakes.

**Comment by tomkralidis** [comment]
Thanks @Amienshxq, this is great. I've added this to KPI C in #72 .

At this point I will turn it over to @josusky for recommendations on possible tooling to programmatically implement spell checking, which will help us in pywcmp.  Python-based packages or API services are preferred.

**Comment by Amienshxq** [comment]
@tomkralidis 
Thanks tom, It's good idea.  
It would be better if there were consistent tool validation.

**Comment by josusky** [comment]
I have googled a bit and found following tools:
- https://pypi.org/project/pyspellchecker - a "native" python spell checker.
- http://hunspell.github.io - a widely used spell checker that has a python binding (https://pypi.org/project/hunspell/)
- http://aspell.net - probably the best open source spell checker, though its python binding looks a bit underdeveloped (https://github.com/WojciechMula/aspell-python)

**Comment by tomkralidis** [comment]
Thanks @josusky.  We can then cover in pywcmp in KPI C implementation once the initial iteration of KPIs are finalized.
