### ISSUE TITLE
Move KPI examples

### ISSUE THREAD

**Issue by amilan17** [wmo-im/wcmp#90]
**Reorganize KPI**
For ease of readability, move XML examples into the Guidance section and add 'Examples' to the title.

**Comment by amilan17** [comment]
@tomkralidis -- I don't remember the rationale/context for this.... Do you?

**Comment by tomkralidis** [comment]
iirc I think we wanted the XML less "up front" in each KPI's respective introduction (XPaths are fine, though).

Closing this one given the KPIs will evolve given WCMP2 (hence GeoJSON).
