### ISSUE TITLE
Improve wording in examples paragraph of KPI 6

### ISSUE THREAD

**Issue by josusky** [wmo-im/wcmp#91]
In the paragraph "Well defined keywords examples" we have several examples but their relation to actual rules is not clear.

I suggest to remove sentence "Check if keyword term is user-defined." and the example that follows:
```xml
  <gmd:MD_Keywords>
    <gmd:keyword>
      <gco:CharacterString>Dewpoint Temperature</gco:CharacterString>
    </gmd:keyword>
  </gmd:MD_Keywords>
```
because it does not correspond to any of the 4 rules in this KPI, and there is already an example for `gmd:MD_Keywords`.

I also suggest to rephrase examples about thesaurus. There are two of them, one with "gco:CharacterString" and one with "gmx:Anchor" but the texts that introduce those examples does not clearly indicate it.

**Comment by josusky** [comment]
@martaguti Please review my changes in commit c991d14 (branch issue-69). While checking the XML snippets I got confused about the relation of the examples to actual validation rules so I have tried to make it clearer.

**Comment by martaguti** [comment]
@josusky that's Ok , If that is clearer to implementation people. 
But I have to change the example all together  as WMO codes.wmo.int will not run GRIB 2 parameter names

**Comment by martaguti** [comment]
@josusky  the rules as they are got me thinking as potentially we could give marks to someone that defines a type on its own (and not a keyword ) which would not make much sense ?

**Comment by josusky** [comment]
@martaguti you have lost me there. Could you give me an example of what you mean by defining own (custom) type?

**Comment by josusky** [comment]
Clarified on a brief telco with @martaguti - the schema does not permit an `gmd:MD_Keywords` element with `gmd:type` but without `gmd:keyword` so we are safe here.
