### ISSUE TITLE
Temporal extent with both time as "indeterminatePosition"

### ISSUE THREAD

**Issue by josusky** [wmo-im/wcmp#98]
**Summary and Purpose**
Quite a lot of existing metadata records have temporal information defined purely with "now" and "before" or "after", for example
```
<gml:TimePeriod gml:id="PeriodProvide">
    <gml:beginPosition indeterminatePosition="before"/>
    <gml:endPosition indeterminatePosition="now"/>
</gml:TimePeriod>
```
or
```
<gml:TimePeriod gml:id="boundingTemporalExtentPeriod">
    <gml:beginPosition indeterminatePosition="now"/>
    <gml:endPosition indeterminatePosition="after"/>
</gml:TimePeriod>
```
The first one refers to the past and the present only, while the latter refers to the present and a future (strictly speaking, that one does not exist yet :-))
Seriously, there are more than 2000 documents (2%) with endPosition indeterminatePosition="after" and about 160 with begin set to "before". Thus, I suggest to accept such constructs - as long as they define a logically non-empty time interval.

**Proposal**
To validate such constructs, I suggest to treat "before" as let say _current date/time minus 24 hours_ and "after" as _current date/time plus 24 hours_. This way both aforementioned constructs will yield a non-empty interval. At the same time complete nonsense like:
```
<gml:TimePeriod gml:id="boundingTemporalExtentPeriod">
    <gml:beginPosition indeterminatePosition="now"/>
    <gml:endPosition indeterminatePosition="before"/>
</gml:TimePeriod>
```
will fail on the test `begin < end` (see [KPI-4](https://github.com/wmo-im/wcmp/blob/master/kpi/004-temporal-information.adoc)).

**Reason**
Lot of data producers generate "real-time" data and have no idea how to set product availability time period. We could recommend them to use a specific construct but for now we should be benevolent at this point. Only complete nonsens needs to be rejected.

**Comment by amilan17** [comment]
@josusky - is this still an open issue?

**Comment by josusky** [comment]
I have not found any records with `<gml:endPosition indeterminatePosition="before"/>`. Thus, this is more a note for WCMP 2.0 design to set clear rules for the temporal extent and its validation in the respective KPI.
